id: 9242876a-41c4-42f8-96f8-ac92d6025406
title: Settings
data:
  site_name: 'Hayley Bech'
  social:
    -
      id: m4c8bqhi
      name: Bluesky
      url: 'https://bsky.app/profile/hayleybech.bsky.social'
      icon: site/social-icons/bluesky-svg.svg
    -
      id: m4c8h8rr
      name: Facebook
      url: 'https://www.facebook.com/hayleybech.me/'
      icon: site/social-icons/facebook.svg
    -
      id: m4c8m9wq
      name: LinkedIn
      url: 'https://www.linkedin.com/in/hayley-bech'
      icon: site/social-icons/linkedin.svg
    -
      id: gyYYJFwP
      name: Github
      url: 'https://github.com/statamic/hayleybech'
      icon: site/social-icons/github.svg
    -
      id: gCaUXBjQ
      name: Email
      url: 'mailto:hayleybech@gmail.com'
      icon: site/social-icons/email.svg

